spring.application.name=backend

# ===============================
# DATABASE CONNECTION (Sử dụng biến môi trường từ file .env)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===============================
# JPA & HIBERNATE CONFIG
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tự động cập nhật bảng trong Database
spring.jpa.hibernate.ddl-auto=update

# Dialect cho MariaDB (chuẩn của XAMPP)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# ===============================
# SERVER CONFIG
# ===============================
server.port=8080
