spring.application.name=backend

# ===============================
# DATABASE CONNECTION (Sử dụng biến môi trường từ file .env)
# ===============================
spring.datasource.url=jdbc:mariadb://localhost:3306/ecommerce_fashion_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===============================
# JPA & HIBERNATE CONFIG
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tự động cập nhật bảng trong Database
spring.jpa.hibernate.ddl-auto=update

# Dialect cho MariaDB (chuẩn của XAMPP)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# ===============================
# SERVER CONFIG
# ===============================
server.port=8080

